name: Run API Tests

on:
  release:
    types: [created]
  workflow_dispatch:
    branches: "*"  
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Build wheel
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        python setup.py bdist_wheel --universal

    - name: Install wheel
      run: |
        pip install dist/*.whl

    - name: Install API test dependencies
      run: |
        python -m pip install -r vecto/api-tests/requirements.txt

    - name: Run API Tests
      env:
        vector_space_id : ${{ secrets.USER_TOKEN }}
        user_token: ${{ secrets.USER_TOKEN }}
        public_token: ${{ secrets.PUBLIC_TOKEN }}
      run: |
        pytest vecto/api-tests/test_user.py
        pytest vecto/api-tests/test_public.py

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: vecto-wheel
        path: dist