name: Run API Tests

on:
  release:
    types: [created]
  pull_request:
    branches: "*"
  workflow_dispatch:
    branches: "*"  
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Build wheel
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        python setup.py bdist_wheel --universal

    - name: Install wheel
      run: |
        pip install dist/*.whl

    - name: Install API test dependencies
      run: |
        python -m pip install -r tests/requirements.txt

    - name: Run API Tests
      env:
        vector_space_id : ${{ secrets.VECTOR_SPACE_ID }}
        user_token: ${{ secrets.USER_TOKEN }}
        vecto_base_url:  ${{ secrets.VECTO_BASE_URL }}
        management_token:  ${{ secrets.MANAGEMENT_TOKEN }}
        VECTO_API_KEY:  ${{ secrets.VECTO_API_KEY }}

      run: |
        pytest tests/test_sdk.py
        pytest tests/test_management.py
        pytest tests/test_vectorspace.py

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: vecto-wheel
        path: dist
