name: Run Secret Tests

on:
  release:
    types: [created]
  workflow_dispatch:
    branches: "*"  
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Build wheel
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        python setup.py bdist_wheel --universal

    - name: Install wheel
      run: |
        pip install dist/*.whl

    - name: Install API test dependencies
      run: |
        python -m pip install -r vecto/api-tests/requirements.txt

    - name: Debug
      run: |
        pwd

    - name: List Packages
      run: |
        pip list

    - name: List Paths
      run: |
        ls

    - name: Run API Tests
      env:
        secret_debug : ${{ secrets.SECRET_DEBUG }}
        secret_int: ${{ secrets.SECRET_INT }}
      run: |
        python vecto/api-tests/test_secret.py